# Travis CI script

language: java

os:
- linux
- osx

sudo: false

env:
  - BUILD_TYPE=default
  - BUILD_TYPE=stable_zmq ZMQ_REPO=zeromq2-x
  - BUILD_TYPE=stable_zmq ZMQ_REPO=zeromq3-x
  - BUILD_TYPE=stable_zmq ZMQ_REPO=zeromq4-x
  - BUILD_TYPE=stable_zmq ZMQ_REPO=zeromq4-1
  - BUILD_TYPE=android
  # As we have errors in bindings/python/test.py I'm suspending this...
  #- BUILD_TYPE=check-py
  - BUILD_TYPE=cmake
  - BUILD_TYPE=bindings BINDING=jni

matrix:
  exclude:
  - env: BUILD_TYPE=bindings BINDING=jni
    os: osx

addons:
  apt:
    packages:
    - uuid-dev
    - valgrind

before_install:
- if [ $TRAVIS_OS_NAME == "osx" ] ; then brew update; brew reinstall ossp-uuid binutils valgrind ; fi

# ZMQ stress tests need more open socket (files) than the usual default
# On OSX, it seems the way to set the max files limit is constantly changing, so
# try to use all known knobs to ensure compatibility across various versions
before_script:
- if [ $TRAVIS_OS_NAME == "osx" ] ; then sudo sysctl -w kern.maxfiles=64000 ; sudo sysctl -w kern.maxfilesperproc=64000 ; sudo launchctl limit maxfiles 64000 64000 ; ulimit -n 64000 ; fi ; ulimit -n 64000
- ./autogen.sh

# Build and check this project according to the BUILD_TYPE
script: ./ci_build.sh
before_deploy: . ./ci_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: mmpmM0uhaMIKjL7ZkZduDOHkhAWA4Ngaq2FtjQVnUXrsCelSObSLe6BwcvvPp7yYGW44mAmoYPEPWAADatt+6bdVCcf0hgSJS02G4EiuxRAOiZ/ffTaAOhaqfmjuwmZ1cftFUFwehS9JEE9Be59Hv+tGnOOZSkxMWhkQ7xTvidQ=
  file_glob: true
  file: ${CZMQ_DEPLOYMENT}
  skip_cleanup: true
  on:
    branch: master
    tags: true
    condition: $TRAVIS_OS_NAME =~ (linux) && $BUILD_TYPE =~ (default|bindings)
