language: c
os:
- linux
- osx
sudo: false
env:
- BUILD_TYPE=default
- BUILD_TYPE=stable_zmq ZMQ_REPO=zeromq2-x
- BUILD_TYPE=stable_zmq ZMQ_REPO=zeromq3-x
- BUILD_TYPE=stable_zmq ZMQ_REPO=zeromq4-x
- BUILD_TYPE=stable_zmq ZMQ_REPO=zeromq4-1
- BUILD_TYPE=android
- BUILD_TYPE=cmake
addons:
  apt:
    packages:
    - uuid-dev
    - valgrind
before_install:
- if [ $TRAVIS_OS_NAME == "osx" ] ; then brew update; brew reinstall ossp-uuid binutils
  valgrind ; fi
before_script:
- if [ $TRAVIS_OS_NAME == "osx" ] ; then sudo sysctl -w kern.maxfiles=64000 ; sudo
  sysctl -w kern.maxfilesperproc=64000 ; sudo launchctl limit maxfiles 64000 64000
  ; ulimit -n 64000 ; fi ; ulimit -n 64000
- ./autogen.sh
script: ./ci_build.sh
before_deploy:
- ./ci_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: jP+22/jUo/n4CebiZuH24iZL62bjwNo6nj7vYCbFcn24RJya7DoBuEtbuNzNsEYxmFz/rQh/z4fmit6x0TAkKr7aH/VoLBZGPqBXv++Fp42RyUPrYS9tasKx/qgAHZ7Vmg03ugWMq1ditme6ZjRAaDVaW/biu6fygUw83RbppaQ/aXlWmYILCo73SCMp7WF3v6VuSR8t7VzU1vZhggC6kvn/W9j0Gza0H3+6zeU0Xw1ZwyiCj+DWXfRi2L7MpVDQZZy9OgTC6SvhqN0b+gPPZz19rrxzrYeToeCbyhbVrwuIJ9Ii1tiF/4ip5bZsUaYy3Yph1XbZfChH4GwuligLwfHGcm5pbGkmz19W4hjREKuE9gbJFPfImTCdaKGAyap2aeCII+Lxp209cZJC53yHaADinpLY7U6f4avfMNaaUku5orG+W1AKmgz8knDSp4seauFw/S2EvfgvOWaPiMAkr6CRwcrBlHPDWNyzlhcAXYIvWLJypcHhmYLgLC5PI3kPA/7LgJZdSVIEurVHwAbsLI+bP6uakt/eD8hpGjcd1amU+WqchSZSSGj5eEr4wMOQczC1AUoIByDPa4nHkeVAZ+4P2SRCL83GiEVWy7io9qDGSXI/nNQ808cYyjXci8J78Ta2jnMnZ/4YVUDIyzblwO/zaKrORYd42UiMhsjKqyI=
  file_glob: true
  file: "${CZMQ_DEPLOYMENT}"
  skip_cleanup: true
  on:
    repo: sappo/czmq
    branch: master
    tags: true
